# Generated by Django 5.1.1 on 2024-09-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSQIQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(null=True)),
                ('participant_name', models.CharField(max_length=250, verbose_name='Nome do participante (social)')),
                ('participant_id', models.CharField(max_length=50, verbose_name='ID do participante')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('bedtime', models.TimeField(max_length=250, verbose_name='1. Durante o último mês, quando você geralmente foi para a cama a noite?')),
                ('time_to_sleep', models.CharField(max_length=250, verbose_name='2. Durante o último mês, quanto tempo (em minutos) você geralmente levou para dormir a noite?')),
                ('wake_time', models.TimeField(max_length=250, verbose_name='3. Durante o último mês, quando você geralmente levantou de manhã?')),
                ('sleep_duration', models.CharField(max_length=250, verbose_name='4. Durante o último mês, quantas horas de sono você teve por noite? (Este pode ser diferente do número de horas que você ficou na cama)')),
                ('difficulty_falling_asleep', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='A) não conseguiu adormecer em até 30 minutos')),
                ('waking_up_night', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='B) acordou no meio da noite ou de manhã cedo')),
                ('bathroom_night', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='C) precisou levantar para ir ao banheiro')),
                ('difficulty_breathing', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='D) não conseguiu respirar confortavelmente')),
                ('coughing_snoring', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='E) tossiu ou roncou forte')),
                ('feeling_cold', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='F) sentiu muito frio')),
                ('feeling_hot', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='G) sentiu muito calor')),
                ('bad_dreams', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='H) teve sonhos ruins')),
                ('pain_at_night', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='I) teve dor')),
                ('other_reasons', models.CharField(blank=True, max_length=100, null=True, verbose_name='J) outra(s) razão(ões), por favor descreva:Com que frequência, durante o último mês, você teve dificuldade para dormir devido a essa razão?')),
                ('sleep_quality', models.IntegerField(choices=[(0, 'Muito boa'), (1, 'Boa'), (2, 'Ruim'), (3, 'Muito ruim')], verbose_name='6. Durante o último mês como você classificaria a qualidade do seu sono de uma maneira geral:')),
                ('sleep_medication_use', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='7. Durante o último mês, com que frequência você tomou medicamento (prescrito ou "por conta própria") para lhe ajudar a dormir?')),
                ('difficulty_staying_awake', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='8. No último mês, que frequência você teve dificuldade para ficar acordado enquanto dirigia, comia ou participava de uma atividade social (festa, reunião de amigos, trabalho, estudo)')),
                ('difficulty_enthusiasm', models.IntegerField(choices=[(0, 'Nenhuma dificuldade'), (1, 'Problema leve'), (2, 'Problema razoável'), (3, 'Grande problema')], verbose_name='9. Durante o último mês, quão problemático foi pra você manter o entusiasmo (ânimo) para fazer as coisas (suas atividades habituais)?')),
                ('partner_presence', models.CharField(choices=[('Não', 'Não'), ('Parceiro ou colega, mas em outro quarto', 'Parceiro ou colega, mas em outro quarto'), ('Parceiro no mesmo quarto, mas em outra cama', 'Parceiro no mesmo quarto, mas em outra cama'), ('Parceiro na mesma cama', 'Parceiro na mesma cama')], max_length=50, verbose_name='10. Você tem um(a) parceiro [esposo(a)] ou colega de quarto?')),
            ],
            options={
                'verbose_name': 'Questionário PSQI',
                'verbose_name_plural': 'Questionários PSQI',
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_sleep', models.IntegerField(default=0)),
                ('sleep_latency', models.IntegerField(default=0)),
                ('sleep_duration', models.IntegerField(default=0)),
                ('sleep_efficiency', models.IntegerField(default=0)),
                ('sleep_disorders', models.IntegerField(default=0)),
                ('sleeping_pills', models.IntegerField(default=0)),
                ('daytime_dysfunction', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psqi_score', to='psqi.psqiquestionnaire')),
            ],
        ),
    ]
