# Generated by Django 5.1.1 on 2024-09-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psqi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psqiquestionnaire',
            name='birth_date',
            field=models.DateField(verbose_name='DATA DE NASCIMENTO'),
        ),
        migrations.AlterField(
            model_name='psqiquestionnaire',
            name='participant_id',
            field=models.IntegerField(verbose_name='ID:'),
        ),
        migrations.AlterField(
            model_name='psqiquestionnaire',
            name='participant_name',
            field=models.CharField(max_length=250, verbose_name='NOME DO PARTICIPANTE (SOCIAL)'),
        ),
    ]
