# Generated by Django 5.1.1 on 2024-09-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psqi', '0002_alter_psqiquestionnaire_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psqiquestionnaire',
            name='other_reasons_choice',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='psqiquestionnaire',
            name='partner_presence',
            field=models.CharField(choices=[(0, 'Não'), (1, 'Parceiro ou colega, mas em outro quarto'), (1, 'Parceiro no mesmo quarto, mas em outra cama'), (1, 'Parceiro na mesma cama')], max_length=50, verbose_name='10. Você tem um(a) parceiro [esposo(a)] ou colega de quarto?'),
        ),
    ]
