# Generated by Django 5.1.1 on 2024-09-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psqi', '0003_psqiquestionnaire_other_reasons_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PSQIQuestionnaire',
            new_name='Questionnaire',
        ),
    ]
